spring:
  application:
    name: release-manager
  profiles:
    active: dev

server:
  port: 9090

release-manager:
  jira-api-user: maduranga.bbnt@gmail.com
  jira-api-key: KqjyNZaozz0EurFgtLWO0826


---
spring:
  profiles:
    - dev

---
spring:
  profiles:
    - prod