spring:
  application:
    name: release-manager
  profiles:
    active: dev

server:
  port: 9090

release-manager:
  jira-api-user: <jira-user>
  jira-api-key: <jirs-access-token>
  github-api-user: <github-user>
  github-api-key: <github-access-token>


---
spring:
  profiles:
    - dev

---
spring:
  profiles:
    - prod