spring:
  application:
    name: release-manager
  profiles:
    active: dev

server:
  port: 8080

release-manager:
  api-user: maduranga.bbnt@gmail.com
  api-key: KqjyNZaozz0EurFgtLWO0826


---
spring:
  profiles:
    - dev

---
spring:
  profiles:
    - prod